/*
 * File: app/store/DictHospitalStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.store.DictHospitalStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ccmz.model.DictHospital',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 0,
            storeId: 'DictHospitalStore',
            model: 'ccmz.model.DictHospital',
            proxy: {
                type: 'ajax',
                url: '/DictHospital/GetData',
                reader: {
                    type: 'json',
                    messageProperty: 'msg',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});