/*
 * File: app/store/ICStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.store.ICStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ccmz.model.IdentityCategory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ICStore',
            model: 'ccmz.model.IdentityCategory',
            data: [
                {
                    value: 1,
                    text: '一类对象',
                    type: 1
                },
                {
                    value: 2,
                    text: '二类对象',
                    type: 1
                },
                {
                    value: 3,
                    text: '三类对象',
                    type: 2
                },
                {
                    value: 4,
                    text: '四类对象',
                    type: 2
                }
            ]
        }, cfg)]);
    }
});