/*
 * File: app/store/ReimSourceStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.store.ReimSourceStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ccmz.model.SystemEnum'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ReimSourceStore',
            model: 'ccmz.model.SystemEnum',
            data: [
                {
                    value: 1,
                    text: '本院'
                },
                {
                    value: 2,
                    text: '外转'
                }
            ]
        }, cfg)]);
    }
});