/*
 * File: app/store/SpecBNStore.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.store.SpecBNStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ccmz.model.SystemEnum'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SpecBNStore',
            model: 'ccmz.model.SystemEnum',
            data: [
                {
                    value: 0,
                    text: '无'
                },
                {
                    value: 1,
                    text: '单次单报'
                },
                {
                    value: 2,
                    text: '未参加基本医疗保险'
                },
                {
                    value: 3,
                    text: '单病种定额付费/低自付大病补助'
                },
                {
                    value: 4,
                    text: '医疗费用包干'
                },
                {
                    value: 5,
                    text: '按床日付费'
                }
            ]
        }, cfg)]);
    }
});