/*
 * File: app/view/MyViewportViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.MyViewportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.myviewport',

    onAppHeaderRender: function(component, eOpts) {
        var me=this;
        ccmz.getApplication().showLoadingMask();
        Ext.Ajax.request({
            url:'/Account/GetCurUserInfo',
            success:function(response,opts){
                var r=Ext.decode(response.responseText);
                var vm=me.getViewModel();
                vm.set("UserName",r.UserName);
                vm.set("CurDept",r.CurDept);

            }});
    }

});
