/*
 * File: app/view/SelWindowViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.SelWindowViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.selwindow',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    data: {
        keyValue: ''
    },

    stores: {
        stdDiseaseStore: {
            remoteFilter: true,
            remoteSort: true,
            model: 'ccmz.model.DictStdDisease',
            proxy: {
                type: 'ajax',
                extraParams: {
                    searchKey: null
                },
                timeout: 60000,
                url: '/DictStdDisease/GetData',
                reader: {
                    type: 'json',
                    messageProperty: 'msg',
                    rootProperty: 'data'
                }
            }
        }
    }

});