/*
 * File: app/view/SelWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.SelWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.selwindow',

    requires: [
        'ccmz.view.SelWindowViewModel',
        'ccmz.view.SelWindowViewController',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.selection.RowModel'
    ],

    controller: 'selwindow',
    viewModel: {
        type: 'selwindow'
    },
    height: 438,
    width: 655,
    title: '选择',
    modal: true,
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            defaults: {
                width: 70
            },
            items: [
                {
                    xtype: 'button',
                    ui: 'default-toolbar-small',
                    text: '清除',
                    listeners: {
                        click: {
                            fn: 'onClearClick',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    ui: 'default-toolbar-small',
                    text: '确定',
                    bind: {
                        disabled: '{!grid.selection}'
                    },
                    listeners: {
                        click: {
                            fn: 'onOKClick',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'button',
                    ui: 'default-toolbar-small',
                    text: '取消',
                    listeners: {
                        click: 'onCancelClick'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            dock: 'top',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'textfield',
                    reference: 'txtKeyValue',
                    padding: '5 0 0 10',
                    fieldLabel: '查询',
                    labelWidth: 60,
                    selectOnFocus: true,
                    bind: {
                        value: '{keyValue}'
                    }
                },
                {
                    xtype: 'container',
                    padding: '0 0 0 20',
                    items: [
                        {
                            xtype: 'button',
                            reference: 'btnQuery',
                            text: '查询',
                            listeners: {
                                click: {
                                    fn: 'onBtnQueryClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            reference: 'grid',
            title: '疾病字典',
            forceFit: true,
            bind: {
                store: '{stdDiseaseStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Code',
                    text: '代码'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ShortName',
                    text: '简称'
                },
                {
                    xtype: 'gridcolumn',
                    width: 279,
                    dataIndex: 'Name',
                    text: '名称'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    bind: {
                        store: '{stdDiseaseStore}'
                    }
                }
            ],
            selModel: {
                selType: 'rowmodel'
            },
            listeners: {
                itemdblclick: {
                    fn: 'onGridpanelItemDblClick',
                    scope: 'controller'
                }
            }
        }
    ],
    listeners: {
        show: {
            fn: 'onWindowShow',
            scope: 'controller'
        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.close();
    }

});