/*
 * File: app/view/SelWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.SelWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.selwindow',

    onClearClick: function(button, e, eOpts) {
        var win=this.getView();
        Ext.callback(win.doClearCallback,win.scope);
        win.close();
    },

    onOKClick: function(button, e, eOpts) {
        var d=this.lookupReference("grid").selection;
        var win=this.getView();
        Ext.callback(win.doOkCallback,win.scope,[d]);
        win.close();
    },

    onBtnQueryClick: function(button, e, eOpts) {
        var vm=this.getViewModel();
        var store=vm.getStore('stdDiseaseStore');
        var proxy=store.getProxy();
        proxy.extraParams.searchKey=vm.get('keyValue');
        store.loadPage(1);
    },

    onGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        this.onOKClick();
    },

    onWindowShow: function(component, eOpts) {
        var txtKey=this.lookupReference("txtKeyValue");
        txtKey.focus();
    }

});
