/*
 * File: app/model/Bn_TreatmentReimburse.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.model.Bn_TreatmentReimburse', {
    extend: 'Ext.data.Model',
    alias: 'model.bn_treatmentreimburse',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    idProperty: 'ID',

    fields: [
        {
            type: 'string',
            name: 'ID'
        },
        {
            type: 'string',
            name: 'Apply_Hospital_ID'
        },
        {
            type: 'string',
            name: 'Reim_NO'
        },
        {
            type: 'string',
            name: 'Sfzh',
            validators: [
                {
                    type: 'length',
                    max: 18,
                    min: 18
                }
            ]
        },
        {
            type: 'int',
            name: 'Medicare_State'
        },
        {
            type: 'string',
            name: 'Person_Code'
        },
        {
            type: 'int',
            name: 'Reim_Source'
        },
        {
            type: 'string',
            name: 'BillNO',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'string',
            name: 'TreatmentHosptial_Code'
        },
        {
            type: 'string',
            name: 'TreatmentHosptial'
        },
        {
            type: 'string',
            name: 'Treatment_NO'
        },
        {
            type: 'int',
            name: 'Reim_Type_ID'
        },
        {
            type: 'date',
            name: 'In_Date'
        },
        {
            type: 'date',
            name: 'Out_Date'
        },
        {
            type: 'date',
            name: 'Medicare_Date'
        },
        {
            type: 'date',
            name: 'TypeIn_Date'
        },
        {
            type: 'float',
            name: 'Medicare_Line'
        },
        {
            type: 'string',
            name: 'StdDisease_Code'
        },
        {
            type: 'string',
            name: 'StdDisease_Name'
        },
        {
            type: 'float',
            name: 'ZL_Money'
        },
        {
            type: 'float',
            name: 'ZF_Money'
        },
        {
            type: 'float',
            name: 'YLZ_Money'
        },
        {
            type: 'float',
            name: 'GR_Money'
        },
        {
            type: 'float',
            name: 'YBBX_Money'
        },
        {
            type: 'float',
            name: 'XNH_Money'
        },
        {
            type: 'string',
            name: 'Family_Code'
        },
        {
            type: 'date',
            name: 'Apply_Date'
        },
        {
            type: 'float',
            name: 'DBBX_Money'
        },
        {
            type: 'string',
            name: 'Card_NO'
        },
        {
            type: 'int',
            name: 'Finish_Flag',
            persist: false
        },
        {
            type: 'string',
            name: 'SfLb'
        },
        {
            type: 'string',
            name: 'JGBM'
        },
        {
            type: 'int',
            name: 'PrintCount',
            persist: false
        },
        {
            type: 'string',
            name: 'Operator_ID',
            persist: false
        },
        {
            type: 'date',
            name: 'Create_Time',
            persist: false
        },
        {
            type: 'string',
            name: 'Pay_Operator_ID',
            persist: false
        },
        {
            type: 'date',
            name: 'Finish_Date',
            persist: false
        },
        {
            type: 'float',
            name: 'SelfBaseMoney',
            persist: false
        },
        {
            type: 'float',
            name: 'YLJZ_Money',
            persist: false
        },
        {
            type: 'date',
            name: 'Cancel_Date',
            persist: false
        },
        {
            type: 'string',
            name: 'Cancel_Operator_ID',
            persist: false
        },
        {
            type: 'float',
            name: 'YBHG_Money',
            persist: false
        },
        {
            type: 'float',
            name: 'SelfBaseMoney_Total',
            persist: false
        },
        {
            type: 'float',
            name: 'YLJZ_Money_Total',
            persist: false
        }
    ],

    proxy: {
        type: 'ajax',
        api: {
            create: '',
            read: '',
            update: '',
            destroy: ''
        },
        reader: {
            type: 'json',
            messageProperty: 'msg',
            rootProperty: 'data'
        }
    }
});