/*
 * File: app/model/Bn_TreatmentReimburse.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.model.Bn_TreatmentReimburse', {
    extend: 'Ext.data.Model',
    alias: 'model.bn_treatmentreimburse',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json',
        'Ext.data.identifier.Uuid'
    ],

    statics: {
        createNewItem: function() {
            var d = ccmz.model.Bn_TreatmentReimburse.create({
                'Operator_ID':ccmz.getApplication().curUser.UserId,
                'Apply_Hospital_ID':ccmz.getApplication().curUser.Hospital.ID,
                'Operator_Name':ccmz.getApplication().curUser.CNName,
                'TreatmentHosptial_Code':ccmz.getApplication().curUser.Hospital.Code,
                'TreatmentHosptial':ccmz.getApplication().curUser.Hospital.Name,
                'TypeIn_Date':new Date(),
                'Apply_Date':new Date()
            });
            return d;
        }
    },

    convertOnSet: false,
    idProperty: 'ID',

    fields: [
        {
            type: 'string',
            name: 'ID'
        },
        {
            type: 'string',
            name: 'Apply_Hospital_ID'
        },
        {
            type: 'string',
            name: 'Reim_NO'
        },
        {
            type: 'string',
            name: 'Sfzh',
            validators: [
                {
                    type: 'length',
                    max: 18,
                    min: 18
                }
            ]
        },
        {
            type: 'int',
            defaultValue: 1,
            name: 'Medicare_State'
        },
        {
            type: 'string',
            name: 'Person_Code'
        },
        {
            type: 'int',
            defaultValue: 2,
            name: 'Reim_Source'
        },
        {
            type: 'string',
            name: 'BillNO',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'string',
            name: 'TreatmentHosptial_Code'
        },
        {
            type: 'string',
            name: 'TreatmentHosptial',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'string',
            name: 'Treatment_NO'
        },
        {
            type: 'int',
            defaultValue: 15,
            name: 'Reim_Type_ID'
        },
        {
            type: 'date',
            name: 'In_Date',
            dateFormat: 'MS',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'date',
            name: 'Out_Date',
            dateFormat: 'MS',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'date',
            name: 'Medicare_Date',
            dateFormat: 'MS',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'date',
            name: 'TypeIn_Date',
            dateFormat: 'MS'
        },
        {
            type: 'float',
            name: 'Medicare_Line'
        },
        {
            type: 'string',
            name: 'StdDisease_Code'
        },
        {
            type: 'string',
            name: 'StdDisease_Name',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'float',
            name: 'ZL_Money'
        },
        {
            type: 'float',
            name: 'ZF_Money'
        },
        {
            type: 'float',
            name: 'YLZ_Money'
        },
        {
            type: 'float',
            name: 'GR_Money'
        },
        {
            type: 'float',
            name: 'YBBX_Money'
        },
        {
            type: 'float',
            name: 'XNH_Money'
        },
        {
            type: 'string',
            name: 'Family_Code',
            validators: [
                {
                    type: 'presence'
                }
            ]
        },
        {
            type: 'date',
            name: 'Apply_Date',
            dateFormat: 'MS'
        },
        {
            type: 'float',
            name: 'DBBX_Money'
        },
        {
            type: 'string',
            name: 'Card_NO'
        },
        {
            type: 'int',
            defaultValue: 0,
            name: 'Finish_Flag'
        },
        {
            type: 'string',
            name: 'SfLb'
        },
        {
            type: 'string',
            name: 'JGBM'
        },
        {
            type: 'int',
            name: 'PrintCount'
        },
        {
            type: 'string',
            name: 'Operator_ID'
        },
        {
            type: 'date',
            allowNull: true,
            name: 'Create_Time',
            dateFormat: 'MS'
        },
        {
            type: 'string',
            name: 'Pay_Operator_ID'
        },
        {
            type: 'date',
            name: 'Finish_Date',
            dateFormat: 'MS'
        },
        {
            type: 'float',
            defaultValue: 0,
            name: 'SelfBaseMoney'
        },
        {
            type: 'float',
            name: 'YLJZ_Money'
        },
        {
            type: 'date',
            name: 'Cancel_Date',
            dateFormat: 'MS'
        },
        {
            type: 'string',
            name: 'Cancel_Operator_ID'
        },
        {
            type: 'float',
            name: 'YBHG_Money'
        },
        {
            type: 'float',
            name: 'SelfBaseMoney_Total'
        },
        {
            type: 'float',
            name: 'YLJZ_Money_Total'
        },
        {
            type: 'int',
            name: 'Spec_BN'
        },
        {
            type: 'float',
            name: 'CYDBBC_Money'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'IdentityType_ID'
        },
        {
            type: 'float',
            name: 'SelBaseMoney_ZY_Total'
        },
        {
            type: 'float',
            name: 'GR_Accout_Pay'
        },
        {
            type: 'float',
            name: 'YB_Other_Pay'
        },
        {
            name: 'Name'
        },
        {
            name: 'Ry_Zt'
        },
        {
            name: 'Operator_Name'
        },
        {
            name: 'Pay_Operator_Name'
        },
        {
            name: 'Cancel_Operator_Name'
        },
        {
            name: 'IdentityType_Name'
        }
    ],

    proxy: {
        type: 'ajax',
        api: {
            create: '/YLJZ/CreateTRItem',
            read: '/YLJZ/GetTRItemById',
            update: '/YLJZ/UpdateTRItems',
            destroy: ''
        },
        reader: {
            type: 'json',
            messageProperty: 'msg',
            rootProperty: 'data'
        },
        writer: {
            type: 'json',
            writeAllFields: true
        }
    },

    identifier: {
        type: 'uuid'
    }
});