/*
 * File: app/model/DictIdentityType.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.model.DictIdentityType', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'ID'
        },
        {
            type: 'int',
            name: 'CategoryID'
        },
        {
            type: 'string',
            name: 'Name'
        },
        {
            type: 'string',
            name: 'ShortName'
        },
        {
            type: 'int',
            name: 'RegType'
        },
        {
            type: 'string',
            name: 'Memo'
        }
    ]
});