/*
 * File: app/model/DictHospital.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.model.DictHospital', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    idProperty: 'ID',

    fields: [
        {
            type: 'string',
            name: 'ID'
        },
        {
            type: 'int',
            name: 'HospitalLevel_ID'
        },
        {
            type: 'string',
            name: 'Name'
        },
        {
            type: 'string',
            name: 'ShortName'
        },
        {
            type: 'string',
            name: 'Code'
        },
        {
            type: 'string',
            name: 'ContactName'
        },
        {
            type: 'string',
            name: 'Tel'
        },
        {
            type: 'string',
            name: 'Address'
        },
        {
            type: 'string',
            name: 'Memo'
        }
    ]
});