/*
 * File: app/view/yljz/TRItem.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRItem', {
    extend: 'Ext.form.Panel',
    alias: 'widget.yljz.tritem',

    requires: [
        'ccmz.view.yljz.TRItemViewModel',
        'ccmz.view.yljz.TRItemViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.field.Display',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar',
        'Ext.ux.IFrame'
    ],

    config: {
        isLoading: null
    },

    controller: 'yljz.tritem',
    viewModel: {
        type: 'yljz.tritem'
    },
    modelValidation: true,
    padding: 5,
    fieldDefaults: {
        labelAlign: 'left'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'bottom',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    margins: '',
                    html: '<h1>长春市城乡医疗救助</h1>',
                    margin: '-5 0 -5 0',
                    style: 'text-align:center;',
                    width: 279,
                    layout: 'fit'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    reference: 'cStatus',
                    margin: '3 0 0 0'
                }
            ]
        },
        {
            xtype: 'fieldset',
            frame: false,
            scrollable: true,
            defaults: {
                padding: 5
            },
            layout: 'column',
            title: '报销凭证',
            items: [
                {
                    xtype: 'container',
                    padding: '0 10 0 10',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'txtSfzh',
                            tabIndex: 1,
                            fieldLabel: '身份证号',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Sfzh}',
                                readOnly: '{Readonly}'
                            },
                            listeners: {
                                specialkey: 'onSfzhPressEnter',
                                change: 'onSfzhChange',
                                blur: 'onSfzhBlur'
                            }
                        },
                        {
                            xtype: 'combobox',
                            tabIndex: 2,
                            padding: '5 0 0 0',
                            fieldLabel: '报销类型',
                            editable: false,
                            valueField: 'value',
                            bind: {
                                value: '{d.Reim_Source}',
                                readOnly: '{Readonly}',
                                store: '{rsStore}'
                            },
                            listeners: {
                                change: 'onReimSourceChange',
                                select: 'onReimSourceSelect'
                            }
                        },
                        {
                            xtype: 'datefield',
                            tabIndex: 6,
                            fieldLabel: '入院时间',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.In_Date}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            tabIndex: 10,
                            fieldLabel: '医疗保障号',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Card_NO}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useThousandSeparator: true,
                            useDecimalSeparator: true,
                            tabIndex: 14,
                            fieldLabel: '医疗总费用',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            minValue: 0,
                            bind: {
                                value: '{d.YLZ_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 18,
                            fieldLabel: '大病保险补偿金额',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.DBBX_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 22,
                            fieldLabel: '个人账户支付',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.GR_Accout_Pay}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'datefield',
                            tabIndex: 26,
                            fieldLabel: '报销时间',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Apply_Date}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            padding: '3 0 0 0 ',
                            fieldLabel: '录入操作员',
                            bind: {
                                value: '{d.Operator_Name}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if(Ext.isDefined(value))
                                return Ext.util.Format.number(value,'0.00');
                            },
                            fieldLabel: '报销基数',
                            bind: {
                                value: '{d.SelfBaseMoney}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '0 10 0 10',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            fieldLabel: '姓名',
                            bind: {
                                value: '{d.Name}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            tabIndex: 3,
                            fieldLabel: '单据号',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.BillNO}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'datefield',
                            tabIndex: 7,
                            fieldLabel: '出院时间',
                            name: 'Out_Date',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Out_Date}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: '疾病代码',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    tabIndex: 11,
                                    name: 'StdDisease_Code',
                                    editable: false,
                                    bind: {
                                        value: '{d.StdDisease_Code}',
                                        readOnly: '{Readonly}'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 0,
                                    tabIndex: 11,
                                    ui: 'default-toolbar-small',
                                    text: '...',
                                    bind: {
                                        disabled: '{Readonly}'
                                    },
                                    listeners: {
                                        click: 'onSelDiseaseClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 15,
                            fieldLabel: '自理费用',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.ZL_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 19,
                            fieldLabel: '医保(农合)报销',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.YBBX_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 23,
                            fieldLabel: '医保其它支付',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.YB_Other_Pay}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if(Ext.isDefined(value))
                                return Ext.util.Format.date(value,'Y-m-d H:i:s');
                            },
                            fieldLabel: '创建时间',
                            bind: {
                                value: '{d.Create_Time}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if(Ext.isDefined(value))
                                return Ext.util.Format.number(value,'0.00');
                            },
                            fieldLabel: '救助金额',
                            bind: {
                                value: '{d.YLJZ_Money}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '0 10 0 10',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            fieldLabel: '身份类别',
                            bind: {
                                value: '{d.SfLb}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            tabIndex: 4,
                            fieldLabel: '就诊医院',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.TreatmentHosptial}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'datefield',
                            tabIndex: 8,
                            fieldLabel: '结算日期',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Medicare_Date}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            reference: 'txtStdDisease_Name',
                            tabIndex: 12,
                            fieldLabel: '疾病名称',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.StdDisease_Name}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 16,
                            fieldLabel: '自费金额',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.ZF_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 20,
                            fieldLabel: '新农合参与补偿金额',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.XNH_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 24,
                            fieldLabel: '个人承担&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            bind: {
                                value: '{CalGR_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '报销操作员',
                            bind: {
                                value: '{d.Pay_Operator_Name}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '作废操作员',
                            bind: {
                                value: '{d.Cancel_Operator_Name}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    padding: '0 10 0 10',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if (!Ext.isDefined(value))
                                return;
                                if(value==='正常'){
                                    return '<b><span style="color:green">'+value+'</spen></b>';
                                }
                                else{
                                    return '<b><span style="color:red">'+value+'</spen></b>';
                                }
                            },
                            flex: 1,
                            fieldLabel: '人员状态',
                            bind: {
                                value: '{d.Ry_Zt}'
                            }
                        },
                        {
                            xtype: 'combobox',
                            tabIndex: 5,
                            fieldLabel: '医疗类别',
                            editable: false,
                            valueField: 'value',
                            bind: {
                                value: '{d.Reim_Type_ID}',
                                readOnly: '{Readonly}',
                                store: '{rtStore}'
                            }
                        },
                        {
                            xtype: 'datefield',
                            tabIndex: 9,
                            fieldLabel: '录入日期',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.TypeIn_Date}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            tabIndex: 13,
                            fieldLabel: '家庭编码',
                            selectOnFocus: true,
                            bind: {
                                value: '{d.Family_Code}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 17,
                            fieldLabel: '起付线',
                            fieldStyle: 'text-align: right;',
                            selectOnFocus: true,
                            decimalPrecision: 0,
                            bind: {
                                value: '{d.Medicare_Line}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            useDecimalSeparator: true,
                            tabIndex: 21,
                            fieldLabel: '新农合参与大病补偿金额',
                            fieldStyle: 'text-align: right;',
                            bind: {
                                value: '{d.CYDBBC_Money}',
                                readOnly: '{Readonly}'
                            }
                        },
                        {
                            xtype: 'combobox',
                            tabIndex: 25,
                            fieldLabel: '特殊情况&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
                            editable: false,
                            valueField: 'value',
                            bind: {
                                value: '{d.Spec_BN}',
                                readOnly: '{Readonly}',
                                store: '{sbnStore}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if(Ext.isDefined(value))
                                return Ext.util.Format.date(value,'Y-m-d H:i:s');
                            },
                            fieldLabel: '报销时间',
                            bind: {
                                value: '{d.Finish_Date}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            renderer: function(value, displayField) {
                                if(Ext.isDefined(value))
                                return Ext.util.Format.date(value,'Y-m-d H:i:s');
                            },
                            fieldLabel: '作废日期',
                            bind: {
                                value: '{d.Cancel_Date}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            defaults: {
                width: 60
            },
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    tabIndex: 27,
                    ui: 'default-toolbar-small',
                    text: '提交',
                    bind: {
                        disabled: '{Readonly}'
                    },
                    listeners: {
                        click: 'onSubmitClick'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 28,
                    text: '重置',
                    bind: {
                        disabled: '{Readonly}'
                    },
                    listeners: {
                        click: 'onResetClick'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 29,
                    width: 100,
                    text: '试算大病保险',
                    bind: {
                        disabled: '{Readonly}'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 30,
                    allowDepress: false,
                    text: '报销',
                    bind: {
                        disabled: '{!CanPay}'
                    },
                    listeners: {
                        click: 'onPayClick'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 31,
                    width: 80,
                    text: '打印凭证',
                    bind: {
                        disabled: '{!IsPayed}'
                    },
                    listeners: {
                        click: 'onPrintClick'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 32,
                    text: '作废',
                    bind: {
                        disabled: '{!IsPayed}'
                    },
                    listeners: {
                        click: 'onCancelClick'
                    }
                },
                {
                    xtype: 'button',
                    tabIndex: 33,
                    width: 80,
                    text: '继续录入'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onFormAfterRender'
    }

});