/*
 * File: app/view/yljz/TRItemViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRItemViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.yljz.tritem',

    requires: [
        'Ext.app.bind.Formula',
        'Ext.data.ChainedStore'
    ],

    links: {
        
    },

    formulas: {
        BaseMoneyDisplay: function(get) {
            return Ext.util.Format.number(get('d.SelfBaseMoney'),'0.00');
        },
        CanPay: function(get) {
            return get('d.Finish_Flag')===0 && Ext.isDefined(get('d.Create_Time'));
        },
        Readonly: {
            get: function(data) {
                return data===1 || data===2;
            },
            bind: '{d.Finish_Flag}'
        },
        IsPayed: {
            get: function(data) {
                return data===1;
            },
            bind: '{d.Finish_Flag}'
        },
        IsCanceled: {
            get: function(data) {
                return data===2;
            },
            bind: '{d.Finish_Flag}'
        }
    },
    stores: {
        rsStore: {
            source: 'ReimSourceStore'
        },
        rtStore: {
            source: 'ReimburseTypeStore'
        },
        sbnStore: {
            source: 'SpecBNStore'
        }
    }

});