/*
 * File: app/view/yljz/TRItem.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRItem', {
    extend: 'Ext.form.Panel',
    alias: 'widget.yljz.tritem',

    requires: [
        'ccmz.view.yljz.TRItemViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.field.Display',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    viewModel: {
        type: 'yljz.tritem'
    },
    modelValidation: true,
    padding: 5,
    fieldDefaults: {
        labelAlign: 'left'
    },

    items: [
        {
            xtype: 'fieldset',
            frame: false,
            scrollable: true,
            defaults: {
                padding: 5
            },
            layout: 'column',
            title: '报销凭证',
            items: [
                {
                    xtype: 'container',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: '身份证号'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: '报销类型'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: '入院时间'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '医疗保障号'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '医疗总费用'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '大病保险补偿金额'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '个人账户支付'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: '报销时间'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '录入操作员'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '报销基数'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            fieldLabel: '姓名'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '单据号'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: '出院时间'
                        },
                        {
                            xtype: 'fieldcontainer',
                            fieldLabel: '疾病代码',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1
                                },
                                {
                                    xtype: 'button',
                                    flex: 0,
                                    text: '...'
                                }
                            ]
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '自理费用'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '医保(农合)报销'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '医保其它支付'
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '创建时间'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '救助金额'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            fieldLabel: '身份类别'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '就诊医院'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: '结算日期'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '疾病名称'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '自费金额'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '新农合参与补偿金额'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '个人承担&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '报销操作员'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '作废操作员'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    width: '25%',
                    defaults: {
                        width: 250,
                        labelWidth: 80
                    },
                    layout: {
                        type: 'vbox',
                        padding: ''
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            fieldLabel: '人员状态',
                            value: ''
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: '医疗类别'
                        },
                        {
                            xtype: 'datefield',
                            fieldLabel: '录入日期'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '家庭编码'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '起付线'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: '新农合参与大病补偿金额'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: '特殊情况&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                        },
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            hideEmptyLabel: false
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '报销时间'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: '作废日期'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            defaults: {
                width: 60
            },
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    text: '提交'
                },
                {
                    xtype: 'button',
                    text: '重置'
                },
                {
                    xtype: 'button',
                    width: 100,
                    text: '试算大病保险'
                },
                {
                    xtype: 'button',
                    text: '报销'
                },
                {
                    xtype: 'button',
                    width: 80,
                    text: '打印凭证'
                },
                {
                    xtype: 'button',
                    text: '作废'
                },
                {
                    xtype: 'button',
                    width: 80,
                    text: '继续录入'
                }
            ]
        }
    ]

});