/*
 * File: app/view/yljz/TRItemViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRItemViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.yljz.tritem',

    requires: [
        'Ext.data.ChainedStore',
        'Ext.app.bind.Formula',
        'ccmz.view.SelWindow'
    ],

    links: {
        
    },

    stores: {
        rsStore: {
            source: 'ReimSourceStore'
        },
        rtStore: {
            source: 'ReimburseTypeStore'
        },
        sbnStore: {
            source: 'SpecBNStore'
        }
    },
    formulas: {
        CanPay: function(get) {

            return get('d.Finish_Flag')===0 && get('d.Create_Time')!==null;
        },
        Readonly: {
            get: function(data) {
                return data===1 || data===2;
            },
            bind: '{d.Finish_Flag}'
        },
        IsPayed: {
            get: function(data) {
                return data===1;
            },
            bind: '{d.Finish_Flag}'
        },
        IsCanceled: {
            get: function(data) {
                return data===2;
            },
            bind: '{d.Finish_Flag}'
        },
        CalGR_Money: {
            get: function(get) {
                return get('d.YLZ_Money')-get('d.YBBX_Money')-get('d.DBBX_Money')-get('d.GR_Accout_Pay')-get('d.YB_Other_Pay');
            },
            set: function(value) {
                this.set('d.GR_Money',value);
            }
        }
    }

});