/*
 * File: app/view/yljz/TRItemViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRItemViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.yljz.tritem',

    onSubmitClick: function(button, e, eOpts) {
        var vm=this.getViewModel();
        alert(vm.get('d.In_Date'));
        alert(vm.get('d.Out_Date'));
    },

    onFormAfterRender: function(component, eOpts) {
        var txtSfzh = this.lookupReference('txtSfzh');
        txtSfzh.focus(false,500);
    }

});
