/*
 * File: app/view/yljz/TRQuery.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRQuery', {
    extend: 'Ext.container.Container',
    alias: 'widget.yljztrquery',

    requires: [
        'ccmz.view.yljz.TRQueryViewModel',
        'ccmz.view.yljz.TRQueryViewController',
        'ccmz.view.TreePicker',
        'ccmz.view.CompareControl',
        'ccmz.view.DatePickerControl',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number',
        'Ext.toolbar.Paging',
        'ccmz.store.DictGovermentDeptStore'
    ],

    config: {
        QueryType: 0,
        showDetailLink: true
    },

    controller: 'yljz.trquery',
    viewModel: {
        type: 'yljz.trquery'
    },
    height: 635,
    width: 1110,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    listeners: {
        afterrender: 'onContainerAfterRender'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'panel',
                        margin: 5,
                        padding: 0,
                        defaults: {
                            margin: '5 5 5 5'
                        },
                        layout: 'anchor',
                        collapsed: false,
                        collapsible: true,
                        title: '查询条件',
                        items: [
                            {
                                xtype: 'container',
                                defaults: {
                                    padding: '0 0 0 5'
                                },
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        fieldLabel: '身份证号',
                                        labelWidth: 60,
                                        bind: {
                                            value: '{sfzh}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        reference: 'cboReimSource',
                                        fieldLabel: '报销类型',
                                        labelWidth: 70,
                                        queryMode: 'local',
                                        store: 'ReimSourceStore',
                                        valueField: 'value',
                                        bind: {
                                            value: '{reim_source}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        fieldLabel: '救助类别',
                                        labelWidth: 60,
                                        queryMode: 'local',
                                        store: 'ReimburseTypeStore',
                                        valueField: 'value',
                                        bind: {
                                            value: '{reim_type}'
                                        }
                                    },
                                    me.processOrg({
                                        xtype: 'treepicker',
                                        displayField: 'text',
                                        reference: 'org',
                                        padding: '0 0 0 5',
                                        fieldLabel: '行政区划',
                                        labelWidth: 60,
                                        selectOnFocus: true,
                                        flex: 1,
                                        bind: {
                                            value: '{dept_id}'
                                        }
                                    }),
                                    me.processCboHospital({
                                        xtype: 'combobox',
                                        flex: 1,
                                        reference: 'cboHospital',
                                        fieldLabel: '医院',
                                        labelWidth: 90,
                                        fieldStyle: '',
                                        allQuery: 'all',
                                        displayField: 'Name',
                                        valueField: 'ID',
                                        bind: {
                                            value: '{apply_hospital}'
                                        },
                                        listeners: {
                                            afterrender: 'onCboHospitalAfterRender'
                                        }
                                    })
                                ]
                            },
                            {
                                xtype: 'container',
                                defaults: {
                                    padding: '0 0 0 5'
                                },
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        fieldLabel: '人员姓名',
                                        labelWidth: 60,
                                        bind: {
                                            value: '{name}'
                                        }
                                    },
                                    {
                                        xtype: 'comparecontrol',
                                        fieldLabel: '医疗总费用',
                                        labelWidth: 70,
                                        flex: 1,
                                        bind: {
                                            symbol: '{ylz_symbol}',
                                            value: '{ylz_value}'
                                        }
                                    },
                                    {
                                        xtype: 'comparecontrol',
                                        fieldLabel: '个人承担',
                                        labelWidth: 60,
                                        flex: 1,
                                        bind: {
                                            symbol: '{gr_symbol}',
                                            value: '{gr_value}'
                                        }
                                    },
                                    {
                                        xtype: 'comparecontrol',
                                        fieldLabel: '民政救助',
                                        labelWidth: 60,
                                        flex: 1,
                                        bind: {
                                            symbol: '{yljz_symbol}',
                                            value: '{yljz_value}'
                                        }
                                    },
                                    {
                                        xtype: 'comparecontrol',
                                        fieldLabel: '累计民政救助',
                                        labelWidth: 90,
                                        flex: 1,
                                        bind: {
                                            symbol: '{sum_yljz_symbol}',
                                            value: '{sum_yljz_value}'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                defaults: {
                                    padding: '0 0 0 5'
                                },
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        fieldLabel: '保障对象',
                                        labelWidth: 60,
                                        queryMode: 'local',
                                        store: 'RegTypeStore',
                                        valueField: 'value',
                                        bind: {
                                            value: '{reg_type}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        fieldLabel: '对象范围',
                                        labelWidth: 70,
                                        queryMode: 'local',
                                        store: 'ICTypeStore',
                                        valueField: 'value',
                                        bind: {
                                            value: '{ic_type}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        fieldLabel: '身份分类',
                                        labelWidth: 60,
                                        queryMode: 'local',
                                        valueField: 'value',
                                        bind: {
                                            value: '{ic}',
                                            store: '{IC}'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        flex: 1,
                                        fieldLabel: '人员类别',
                                        labelWidth: 60,
                                        allQuery: 'all',
                                        displayField: 'Name',
                                        valueField: 'ID',
                                        bind: {
                                            value: '{idt_type}',
                                            store: '{DIT}'
                                        }
                                    },
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        fieldLabel: '疾病名称',
                                        labelWidth: 90,
                                        bind: {
                                            value: '{disease_name}'
                                        }
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                defaults: {
                                    padding: '0 0 0 5'
                                },
                                layout: {
                                    type: 'hbox',
                                    align: 'middle'
                                },
                                items: [
                                    {
                                        xtype: 'datepickercontrol',
                                        fieldLabel: '录入日期',
                                        labelWidth: 60,
                                        bind: {
                                            value1: '{apply_date1}',
                                            value2: '{apply_date2}'
                                        }
                                    },
                                    {
                                        xtype: 'datepickercontrol',
                                        reference: 'dtpFinishDate',
                                        fieldLabel: '报销日期',
                                        labelWidth: 60,
                                        bind: {
                                            value1: '{finish_date1}',
                                            value2: '{finish_date2}'
                                        }
                                    },
                                    {
                                        xtype: 'datepickercontrol',
                                        reference: 'dtpCancelDate',
                                        fieldLabel: '作废日期',
                                        labelWidth: 60,
                                        bind: {
                                            value1: '{cancel_date1}',
                                            value2: '{cancel_date2}'
                                        }
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: {
                                            type: 'hbox',
                                            align: 'middle',
                                            pack: 'end'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                margin: '0 10 0 0',
                                                ui: 'default-toolbar-small',
                                                text: '查询数据',
                                                listeners: {
                                                    click: 'onQueryClick'
                                                }
                                            },
                                            {
                                                xtype: 'button',
                                                ui: 'default-toolbar-small',
                                                text: '查看报表',
                                                listeners: {
                                                    click: 'onReportClick'
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ],
                        listeners: {
                            render: 'onConditionPanelRender'
                        }
                    },
                    {
                        xtype: 'gridpanel',
                        flex: 1,
                        title: '查询结果',
                        titleCollapse: true,
                        columnLines: true,
                        bind: {
                            store: '{GridData}'
                        },
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                    var p=this.findParentByType('yljztrquery');
                                    if (p.showDetailLink){
                                        return '<a href="#">'+value+'</a>';
                                    }
                                    else{
                                        return value;
                                    }
                                },
                                width: 110,
                                dataIndex: 'Reim_NO',
                                text: '凭证编号'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 120,
                                dataIndex: 'Family_Code',
                                text: '家庭编码'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 150,
                                dataIndex: 'Sfzh',
                                text: '身份证号'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 70,
                                dataIndex: 'Name',
                                text: '姓名'
                            },
                            {
                                xtype: 'gridcolumn',
                                renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                    var r=this.lookupController().lookupReference('cboReimSource').getStore().findRecord('value',value);
                                    if (r){
                                        return r.data.text;
                                    }
                                    else{
                                        return value;
                                    }
                                },
                                width: 70,
                                dataIndex: 'Reim_Source',
                                text: '报销类型'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 150,
                                dataIndex: 'TreatmentHosptial',
                                text: '就诊医院'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 80,
                                dataIndex: 'SfLb',
                                text: '身份类别'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 150,
                                dataIndex: 'StdDisease_Name',
                                text: '诊断疾病名称'
                            },
                            {
                                xtype: 'datecolumn',
                                width: 90,
                                dataIndex: 'In_Date',
                                text: '入院时间',
                                format: 'Y/m/d'
                            },
                            {
                                xtype: 'datecolumn',
                                width: 90,
                                dataIndex: 'Out_Date',
                                text: '出院时间',
                                format: 'Y/m/d'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'YLZ_Money',
                                text: '医疗总费用'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'Medicare_Line',
                                text: '起付线'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'ZL_Money',
                                text: '自理费用'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'ZF_Money',
                                text: '自费(不参与补偿)'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'YBBX_Money',
                                text: '医院(农合)报销'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'YBHG_Money',
                                text: '大额合规费用'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'CYDBBC_Money',
                                text: '参与大病补偿'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'DBBX_Money',
                                text: '大病保险补偿'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'XNH_Money',
                                text: '新农合参与补偿'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'GR_Money',
                                text: '个人承担'
                            },
                            {
                                xtype: 'numbercolumn',
                                width: 80,
                                dataIndex: 'YLJZ_Money',
                                text: '民政补偿'
                            },
                            {
                                xtype: 'datecolumn',
                                width: 90,
                                dataIndex: 'Finish_Date',
                                text: '民政报销时间',
                                format: 'Y/m/d'
                            },
                            {
                                xtype: 'datecolumn',
                                width: 90,
                                dataIndex: 'TypeIn_Date',
                                text: '录入日期',
                                format: 'Y/m/d'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 150,
                                dataIndex: 'Apply_Hospital_Name',
                                text: '垫付医院'
                            }
                        ],
                        dockedItems: [
                            {
                                xtype: 'pagingtoolbar',
                                dock: 'bottom',
                                width: 360,
                                bind: {
                                    store: '{GridData}'
                                },
                                items: [
                                    {
                                        xtype: 'textfield',
                                        width: 100,
                                        fieldLabel: 'Label'
                                    }
                                ]
                            }
                        ],
                        listeners: {
                            cellclick: 'onGridpanelCellClick'
                        }
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processOrg: function(config) {
        var s=Ext.create('ccmz.store.DictGovermentDeptStore');
        Ext.applyIf(config,{store:s});
        return config;
    },

    processCboHospital: function(config) {
        var s=Ext.create('ccmz.store.DictHospitalStore',{autoLoad:false});
        s.getProxy().setUrl('/DictHospital/GetDataByUser');
        config=Ext.apply(config,{store:s});
        return config;
    }

});