/*
 * File: app/view/yljz/TRQueryViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ccmz.view.yljz.TRQueryViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.yljz.trquery',

    requires: [
        'Ext.data.ChainedStore',
        'Ext.util.Filter',
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    data: {
        sfzh: '',
        reim_source: null,
        reim_type: null,
        dept_id: '',
        apply_hospital: null,
        name: '',
        ylz_symbol: '>',
        ylz_value: '',
        gr_symbol: '>',
        gr_value: '',
        yljz_symbol: '>',
        yljz_value: '',
        sum_yljz_symbol: '>',
        sum_yljz_value: '',
        reg_type: null,
        ic_type: null,
        ic: null,
        idt_type: null,
        disease_name: '',
        apply_date1: null,
        apply_date2: null,
        finish_date1: null,
        finish_date2: null,
        cancel_date1: null,
        cancel_date2: null
    },

    stores: {
        IC: {
            source: 'ICStore',
            filters: {
                disableOnEmpty: true,
                exactMatch: true,
                property: 'type',
                value: '{ic_type}'
            }
        },
        DIT: {
            pageSize: 0,
            model: 'ccmz.model.IdentityCategory',
            proxy: {
                type: 'ajax',
                url: '/DictIdentityType/GetData',
                reader: {
                    type: 'json',
                    messageProperty: 'msg',
                    rootProperty: 'data'
                }
            },
            filters: [
                {
                    disableOnEmpty: true,
                    property: 'RegType',
                    value: '{reg_type}'
                },
                {
                    disableOnEmpty: true,
                    property: 'CategoryID',
                    value: '{ic}'
                }
            ]
        },
        GridData: {
            remoteFilter: true,
            remoteSort: true,
            model: 'ccmz.model.Bn_TreatmentReimburse',
            proxy: {
                type: 'ajax',
                url: '/YLJZ/GetData',
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                reader: {
                    type: 'json',
                    messageProperty: 'msg',
                    rootProperty: 'data'
                }
            }
        }
    }

});